project_name: cloudflare-ddns

builds:
  - binary: cloudflare-ddns
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - solaris
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: windows
        goarch: arm64

# brews:
#   - tap:
#       owner: thomasmhofmann
#       name: homebrew-stable
#     folder: Formula
#     homepage: https://github.com/thomasmhofmann/cloudflare-ddns
#     description: Cloudflare Dynamic DNS Updater
#     test: |
#       system "#{bin}/cloudflare-ddns -v"
#     install: |
#       bin.install "cloudflare-ddns"

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md

release:
  github:
    owner: thomasmhofmann
    name: cloudflare-ddns
