name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Note the fetch-depth: 0 option is required for the change log to
          # work correctly with goreleaser.
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.15.6"
      - uses: golangci/golangci-lint-action@v3.3.0
        with:
          version: v1.50.1
      - name: Unit testing
        run: go test ./...
      - uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
